[package]
authors = ["Szymon Jankowski <ja@szymekk.me>"]
edition = "2018"
name = "dumb_gfx_format"
version = "0.1.0"
[dependencies]
byteorder = "*"
image = "0.24.0"
memoffset = "0.6.5"
num = "0.4.0"
snap = "1.0.5"
